apiVersion: vrouter.kojuro.date/v1
kind: VRouterConfig
metadata:
  labels:
    app.kubernetes.io/name: vrouter-operator
    app.kubernetes.io/managed-by: kustomize
  name: vyos-with-operator-config
  namespace: default
spec:
  provider:
    type: kubevirt
    kubevirt:
      name: vyos-with-operator
      namespace: default
  commands: |
    set system host-name 'aaabbbccc'
