apiVersion: vrouter.kojuro.date/v1
kind: VRouterTarget
metadata:
  labels:
    app.kubernetes.io/name: vrouter-operator
    app.kubernetes.io/managed-by: kustomize
  name: vyos-proxmox
  namespace: default
spec:
  provider:
    type: proxmox
    proxmox:
      vmid: 121
      clusterRef:
        name: pve-cluster
        namespace: default
  params:
    hostname: "vyos-proxmox"
