apiVersion: vrouter.kojuro.date/v1
kind: VRouterTemplate
metadata:
  labels:
    app.kubernetes.io/name: vrouter-operator
    app.kubernetes.io/managed-by: kustomize
  name: vroutertemplate-sample
spec:
  # TODO(user): Add fields here
