apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "vrouter-operator.fullname" . }}-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "vrouter-operator.fullname" . }}-serving-cert
  labels:
  {{- include "vrouter-operator.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "vrouter-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-vrouter-kojuro-date-v1-proxmoxcluster
  failurePolicy: Fail
  name: mproxmoxcluster-v1.kb.io
  rules:
  - apiGroups:
    - vrouter.kojuro.date
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - proxmoxclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "vrouter-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-vrouter-kojuro-date-v1-vrouterbinding
  failurePolicy: Fail
  name: mvrouterbinding-v1.kb.io
  rules:
  - apiGroups:
    - vrouter.kojuro.date
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - vrouterbindings
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "vrouter-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-vrouter-kojuro-date-v1-vrouterconfig
  failurePolicy: Fail
  name: mvrouterconfig-v1.kb.io
  rules:
  - apiGroups:
    - vrouter.kojuro.date
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - vrouterconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "vrouter-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-vrouter-kojuro-date-v1-vroutertarget
  failurePolicy: Fail
  name: mvroutertarget-v1.kb.io
  rules:
  - apiGroups:
    - vrouter.kojuro.date
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - vroutertargets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "vrouter-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-vrouter-kojuro-date-v1-vroutertemplate
  failurePolicy: Fail
  name: mvroutertemplate-v1.kb.io
  rules:
  - apiGroups:
    - vrouter.kojuro.date
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - vroutertemplates
  sideEffects: None
