apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "vrouter-operator.fullname" . }}-vroutertarget-editor-role
  labels:
  {{- include "vrouter-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - vrouter.kojuro.date
  resources:
  - vroutertargets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vrouter.kojuro.date
  resources:
  - vroutertargets/status
  verbs:
  - get
