apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "vrouter-operator.fullname" . }}-vrouterbinding-admin-role
  labels:
  {{- include "vrouter-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - vrouter.kojuro.date
  resources:
  - vrouterbindings
  verbs:
  - '*'
- apiGroups:
  - vrouter.kojuro.date
  resources:
  - vrouterbindings/status
  verbs:
  - get
