apiVersion: v1
kind: Service
metadata:
  name: {{ include "vrouter-operator.webhookServiceName" . }}
  labels:
  {{- include "vrouter-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  selector:
    control-plane: controller-manager
    {{- include "vrouter-operator.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.webhookService.ports | toYaml | nindent 2 }}
